[greeter]
background=/usr/share/pixmaps/metta-greeter-logo.png
theme-name=Metta-Dark
icon-theme-name=metta
font-name=Inter 11
xft-antialias=true
xft-hinting=true
clock-format=%H:%M
show-indicators=~host;~spacer;~clock;~spacer;~layout;~session;~a11y;~power
