font_family      JetBrains Mono
font_size        13.0

background            #0A0E0C
foreground            #EAF5EE
selection_background  #2BE383
selection_foreground  #0A0E0C
cursor                #2BE383
cursor_text_color     #0A0E0C

color0  #121815
color1  #FF5C72
color2  #2BE383
color3  #F2B33D
color4  #3FD8E8
color5  #B26CFF
color6  #2BE383
color7  #EAF5EE
color8  #4D5A54
color9  #FF7080
color10 #40FF95
color11 #FFD060
color12 #50E8F5
color13 #C080FF
color14 #40FF95
color15 #FFFFFF

enable_audio_bell     no
visual_bell_duration  0.1
window_padding_width  12
tab_bar_style         powerline
tab_powerline_style   slanted
tab_bar_background    #121815
active_tab_foreground #0A0E0C
active_tab_background #2BE383
inactive_tab_foreground #8FA89A
inactive_tab_background #1A2420

map ctrl+shift+t new_tab
map ctrl+shift+w close_tab
map ctrl+shift+enter new_window
map ctrl+shift+] next_window
map ctrl+shift+[ previous_window
map ctrl+shift+5 launch --location=hsplit
map ctrl+shift+' launch --location=vsplit

background_opacity 0.92
